### ISSUE TITLE
issue in IE - Object doesn't support this property or method

### ISSUE THREAD

**Issue by dexteronomy** [wes/Beautiful-Analytics-Chart#3]
Not sure if this is the appropriate venue to submit this. but figured I'd start here.  I'm using this chart library and it's pretty great.  I am having trouble w/ IE though, and wondering if there is any public knowledge about getting it to work in IE.  

The example I'm having trouble with is here --> http://ec2-50-17-108-110.compute-1.amazonaws.com/technical-solar-data/kwh/day/2012-03-27

Ironically this page works ok in IE --> http://joedesigns.com/labs/Beautiful-Analytics-Chart/   but if you download the source code .zip file, from the site,  it experiences the same "Object doesn't support this property or method"

any thoughts on where to start?

**Comment by dexteronomy** [comment]
ok.. interestingly I found n0nick's fork of this and that works in IE.

**Comment by usman000** [comment]
hy dexter,

Im also facing same issue. Kindly tell me in detail how you fixed it. Plz reply asap.

**Comment by dexteronomy** [comment]
Hi usman - ugh.  it's been a while so I can't recall exactly, but something to do w/ IE not supporting an object that the library used.  n0nick's fork was improved, but still had an issue.  You could see if my version works for you.  I added a handful of customizations for our needs and it works in IE (although not as fluidly).  https://github.com/dexterinteractive/solarmonitoring/blob/master/js/sm_raphael_linechart.js
