### ISSUE TITLE
Using latest version of Raphael breaks caption boxes

### ISSUE THREAD

**Issue by jonesnc** [wes/Beautiful-Analytics-Chart#4]
If I use the latest version of Raphael (2.1.0), I get the following behavior:
![resize bug](http://i.imgur.com/NV3Cl.png)

If I use [version 1.5.2](http://ajax.cdnjs.com/ajax/libs/raphael/1.5.2/raphael-min.js), the behavior shown above is fixed and appears in the correct position.

**Comment by lovesmall** [comment]
I'm facing the same issue.

**Comment by nurzico** [comment]
i'm facing the same issue too :(
